secret_key_base = "$SECRET_KEY_BASE"
rails_env = "RAILS_ENV"
port = "$PORT"

[db]
host = "$(services '.user-provided[0].credentials.url')"
name = "$(services '.user-provided[0].credentials.database')"
user = "$(services '.user-provided[0].credentials.username')"
password = "$(services '.user-provided[0].credentials.password')"
