secret_key_base = "$SECRET_KEY_BASE"
rails_env = "$RAILS_ENV"
port = "$PORT"

[db]
user = "$(service "redmine_production_db" '.credentials.username')"
password = "$(service "redmine_production_db" '.credentials.password')"
host = "$(service "redmine_production_db" '.credentials.host')"
name = "$(service "redmine_production_db" '.credentials.database')"
