port = "$PORT"

[db]
host = "$(services '.user-provided[0].credentials.url')"
name = "$(services '.user-provided[0].name')"
user = "$(services '.user-provided[0].credentials.username')"
password = "$(services '.user-provided[0].credentials.password')"
